


development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: kaibarry
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  username: kaibarry
  password:
